linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  goimports:
    local-prefixes: github.com/caesar-terminal/caesar

issues:
  exclude-dirs:
    - internal/gen
